/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UsersRouteImport } from './routes/users'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as TableRouteImport } from './routes/table'
import { Route as QrTestRouteImport } from './routes/qr-test'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as OverviewRouteImport } from './routes/overview'
import { Route as LogsRouteImport } from './routes/logs'
import { Route as DevicePairingRouteImport } from './routes/device-pairing'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as AuthPromptRouteImport } from './routes/auth-prompt'
import { Route as SplatRouteImport } from './routes/$'
import { Route as IndexRouteImport } from './routes/index'
import { Route as OrgsIndexRouteImport } from './routes/orgs/index'
import { Route as DataTableTreeRouteImport } from './routes/data-table.tree'
import { Route as DashboardSignozRouteImport } from './routes/dashboard/signoz'
import { Route as DashboardProxyTargetsRouteImport } from './routes/dashboard/proxy-targets'
import { Route as AuthSignUpRouteImport } from './routes/auth/sign-up'
import { Route as AuthSignInRouteImport } from './routes/auth/sign-in'
import { Route as AuthCallbackRouteImport } from './routes/auth/callback'
import { Route as DashboardSignozIndexRouteImport } from './routes/dashboard/signoz/index'
import { Route as DashboardSignozTracesRouteImport } from './routes/dashboard/signoz/traces'

const UsersRoute = UsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const TableRoute = TableRouteImport.update({
  id: '/table',
  path: '/table',
  getParentRoute: () => rootRouteImport,
} as any)
const QrTestRoute = QrTestRouteImport.update({
  id: '/qr-test',
  path: '/qr-test',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const OverviewRoute = OverviewRouteImport.update({
  id: '/overview',
  path: '/overview',
  getParentRoute: () => rootRouteImport,
} as any)
const LogsRoute = LogsRouteImport.update({
  id: '/logs',
  path: '/logs',
  getParentRoute: () => rootRouteImport,
} as any)
const DevicePairingRoute = DevicePairingRouteImport.update({
  id: '/device-pairing',
  path: '/device-pairing',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthPromptRoute = AuthPromptRouteImport.update({
  id: '/auth-prompt',
  path: '/auth-prompt',
  getParentRoute: () => rootRouteImport,
} as any)
const SplatRoute = SplatRouteImport.update({
  id: '/$',
  path: '/$',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const OrgsIndexRoute = OrgsIndexRouteImport.update({
  id: '/orgs/',
  path: '/orgs/',
  getParentRoute: () => rootRouteImport,
} as any)
const DataTableTreeRoute = DataTableTreeRouteImport.update({
  id: '/data-table/tree',
  path: '/data-table/tree',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardSignozRoute = DashboardSignozRouteImport.update({
  id: '/signoz',
  path: '/signoz',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardProxyTargetsRoute = DashboardProxyTargetsRouteImport.update({
  id: '/proxy-targets',
  path: '/proxy-targets',
  getParentRoute: () => DashboardRoute,
} as any)
const AuthSignUpRoute = AuthSignUpRouteImport.update({
  id: '/auth/sign-up',
  path: '/auth/sign-up',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthSignInRoute = AuthSignInRouteImport.update({
  id: '/auth/sign-in',
  path: '/auth/sign-in',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthCallbackRoute = AuthCallbackRouteImport.update({
  id: '/auth/callback',
  path: '/auth/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardSignozIndexRoute = DashboardSignozIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardSignozRoute,
} as any)
const DashboardSignozTracesRoute = DashboardSignozTracesRouteImport.update({
  id: '/traces',
  path: '/traces',
  getParentRoute: () => DashboardSignozRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/auth-prompt': typeof AuthPromptRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/device-pairing': typeof DevicePairingRoute
  '/logs': typeof LogsRoute
  '/overview': typeof OverviewRoute
  '/privacy': typeof PrivacyRoute
  '/profile': typeof ProfileRoute
  '/qr-test': typeof QrTestRoute
  '/table': typeof TableRoute
  '/terms': typeof TermsRoute
  '/users': typeof UsersRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/auth/sign-in': typeof AuthSignInRoute
  '/auth/sign-up': typeof AuthSignUpRoute
  '/dashboard/proxy-targets': typeof DashboardProxyTargetsRoute
  '/dashboard/signoz': typeof DashboardSignozRouteWithChildren
  '/data-table/tree': typeof DataTableTreeRoute
  '/orgs': typeof OrgsIndexRoute
  '/dashboard/signoz/traces': typeof DashboardSignozTracesRoute
  '/dashboard/signoz/': typeof DashboardSignozIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/auth-prompt': typeof AuthPromptRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/device-pairing': typeof DevicePairingRoute
  '/logs': typeof LogsRoute
  '/overview': typeof OverviewRoute
  '/privacy': typeof PrivacyRoute
  '/profile': typeof ProfileRoute
  '/qr-test': typeof QrTestRoute
  '/table': typeof TableRoute
  '/terms': typeof TermsRoute
  '/users': typeof UsersRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/auth/sign-in': typeof AuthSignInRoute
  '/auth/sign-up': typeof AuthSignUpRoute
  '/dashboard/proxy-targets': typeof DashboardProxyTargetsRoute
  '/data-table/tree': typeof DataTableTreeRoute
  '/orgs': typeof OrgsIndexRoute
  '/dashboard/signoz/traces': typeof DashboardSignozTracesRoute
  '/dashboard/signoz': typeof DashboardSignozIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/auth-prompt': typeof AuthPromptRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/device-pairing': typeof DevicePairingRoute
  '/logs': typeof LogsRoute
  '/overview': typeof OverviewRoute
  '/privacy': typeof PrivacyRoute
  '/profile': typeof ProfileRoute
  '/qr-test': typeof QrTestRoute
  '/table': typeof TableRoute
  '/terms': typeof TermsRoute
  '/users': typeof UsersRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/auth/sign-in': typeof AuthSignInRoute
  '/auth/sign-up': typeof AuthSignUpRoute
  '/dashboard/proxy-targets': typeof DashboardProxyTargetsRoute
  '/dashboard/signoz': typeof DashboardSignozRouteWithChildren
  '/data-table/tree': typeof DataTableTreeRoute
  '/orgs/': typeof OrgsIndexRoute
  '/dashboard/signoz/traces': typeof DashboardSignozTracesRoute
  '/dashboard/signoz/': typeof DashboardSignozIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$'
    | '/auth-prompt'
    | '/dashboard'
    | '/device-pairing'
    | '/logs'
    | '/overview'
    | '/privacy'
    | '/profile'
    | '/qr-test'
    | '/table'
    | '/terms'
    | '/users'
    | '/auth/callback'
    | '/auth/sign-in'
    | '/auth/sign-up'
    | '/dashboard/proxy-targets'
    | '/dashboard/signoz'
    | '/data-table/tree'
    | '/orgs'
    | '/dashboard/signoz/traces'
    | '/dashboard/signoz/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/$'
    | '/auth-prompt'
    | '/dashboard'
    | '/device-pairing'
    | '/logs'
    | '/overview'
    | '/privacy'
    | '/profile'
    | '/qr-test'
    | '/table'
    | '/terms'
    | '/users'
    | '/auth/callback'
    | '/auth/sign-in'
    | '/auth/sign-up'
    | '/dashboard/proxy-targets'
    | '/data-table/tree'
    | '/orgs'
    | '/dashboard/signoz/traces'
    | '/dashboard/signoz'
  id:
    | '__root__'
    | '/'
    | '/$'
    | '/auth-prompt'
    | '/dashboard'
    | '/device-pairing'
    | '/logs'
    | '/overview'
    | '/privacy'
    | '/profile'
    | '/qr-test'
    | '/table'
    | '/terms'
    | '/users'
    | '/auth/callback'
    | '/auth/sign-in'
    | '/auth/sign-up'
    | '/dashboard/proxy-targets'
    | '/dashboard/signoz'
    | '/data-table/tree'
    | '/orgs/'
    | '/dashboard/signoz/traces'
    | '/dashboard/signoz/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SplatRoute: typeof SplatRoute
  AuthPromptRoute: typeof AuthPromptRoute
  DashboardRoute: typeof DashboardRouteWithChildren
  DevicePairingRoute: typeof DevicePairingRoute
  LogsRoute: typeof LogsRoute
  OverviewRoute: typeof OverviewRoute
  PrivacyRoute: typeof PrivacyRoute
  ProfileRoute: typeof ProfileRoute
  QrTestRoute: typeof QrTestRoute
  TableRoute: typeof TableRoute
  TermsRoute: typeof TermsRoute
  UsersRoute: typeof UsersRoute
  AuthCallbackRoute: typeof AuthCallbackRoute
  AuthSignInRoute: typeof AuthSignInRoute
  AuthSignUpRoute: typeof AuthSignUpRoute
  DataTableTreeRoute: typeof DataTableTreeRoute
  OrgsIndexRoute: typeof OrgsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/users': {
      id: '/users'
      path: '/users'
      fullPath: '/users'
      preLoaderRoute: typeof UsersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/table': {
      id: '/table'
      path: '/table'
      fullPath: '/table'
      preLoaderRoute: typeof TableRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/qr-test': {
      id: '/qr-test'
      path: '/qr-test'
      fullPath: '/qr-test'
      preLoaderRoute: typeof QrTestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/overview': {
      id: '/overview'
      path: '/overview'
      fullPath: '/overview'
      preLoaderRoute: typeof OverviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/logs': {
      id: '/logs'
      path: '/logs'
      fullPath: '/logs'
      preLoaderRoute: typeof LogsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/device-pairing': {
      id: '/device-pairing'
      path: '/device-pairing'
      fullPath: '/device-pairing'
      preLoaderRoute: typeof DevicePairingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth-prompt': {
      id: '/auth-prompt'
      path: '/auth-prompt'
      fullPath: '/auth-prompt'
      preLoaderRoute: typeof AuthPromptRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$': {
      id: '/$'
      path: '/$'
      fullPath: '/$'
      preLoaderRoute: typeof SplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/orgs/': {
      id: '/orgs/'
      path: '/orgs'
      fullPath: '/orgs'
      preLoaderRoute: typeof OrgsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/data-table/tree': {
      id: '/data-table/tree'
      path: '/data-table/tree'
      fullPath: '/data-table/tree'
      preLoaderRoute: typeof DataTableTreeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/signoz': {
      id: '/dashboard/signoz'
      path: '/signoz'
      fullPath: '/dashboard/signoz'
      preLoaderRoute: typeof DashboardSignozRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/proxy-targets': {
      id: '/dashboard/proxy-targets'
      path: '/proxy-targets'
      fullPath: '/dashboard/proxy-targets'
      preLoaderRoute: typeof DashboardProxyTargetsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/auth/sign-up': {
      id: '/auth/sign-up'
      path: '/auth/sign-up'
      fullPath: '/auth/sign-up'
      preLoaderRoute: typeof AuthSignUpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/sign-in': {
      id: '/auth/sign-in'
      path: '/auth/sign-in'
      fullPath: '/auth/sign-in'
      preLoaderRoute: typeof AuthSignInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/callback': {
      id: '/auth/callback'
      path: '/auth/callback'
      fullPath: '/auth/callback'
      preLoaderRoute: typeof AuthCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/signoz/': {
      id: '/dashboard/signoz/'
      path: '/'
      fullPath: '/dashboard/signoz/'
      preLoaderRoute: typeof DashboardSignozIndexRouteImport
      parentRoute: typeof DashboardSignozRoute
    }
    '/dashboard/signoz/traces': {
      id: '/dashboard/signoz/traces'
      path: '/traces'
      fullPath: '/dashboard/signoz/traces'
      preLoaderRoute: typeof DashboardSignozTracesRouteImport
      parentRoute: typeof DashboardSignozRoute
    }
  }
}

interface DashboardSignozRouteChildren {
  DashboardSignozTracesRoute: typeof DashboardSignozTracesRoute
  DashboardSignozIndexRoute: typeof DashboardSignozIndexRoute
}

const DashboardSignozRouteChildren: DashboardSignozRouteChildren = {
  DashboardSignozTracesRoute: DashboardSignozTracesRoute,
  DashboardSignozIndexRoute: DashboardSignozIndexRoute,
}

const DashboardSignozRouteWithChildren = DashboardSignozRoute._addFileChildren(
  DashboardSignozRouteChildren,
)

interface DashboardRouteChildren {
  DashboardProxyTargetsRoute: typeof DashboardProxyTargetsRoute
  DashboardSignozRoute: typeof DashboardSignozRouteWithChildren
}

const DashboardRouteChildren: DashboardRouteChildren = {
  DashboardProxyTargetsRoute: DashboardProxyTargetsRoute,
  DashboardSignozRoute: DashboardSignozRouteWithChildren,
}

const DashboardRouteWithChildren = DashboardRoute._addFileChildren(
  DashboardRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SplatRoute: SplatRoute,
  AuthPromptRoute: AuthPromptRoute,
  DashboardRoute: DashboardRouteWithChildren,
  DevicePairingRoute: DevicePairingRoute,
  LogsRoute: LogsRoute,
  OverviewRoute: OverviewRoute,
  PrivacyRoute: PrivacyRoute,
  ProfileRoute: ProfileRoute,
  QrTestRoute: QrTestRoute,
  TableRoute: TableRoute,
  TermsRoute: TermsRoute,
  UsersRoute: UsersRoute,
  AuthCallbackRoute: AuthCallbackRoute,
  AuthSignInRoute: AuthSignInRoute,
  AuthSignUpRoute: AuthSignUpRoute,
  DataTableTreeRoute: DataTableTreeRoute,
  OrgsIndexRoute: OrgsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
