name: openziti
services:
  golang-proxy:
    build:
      context: .
      dockerfile: ./Dockerfile
    container_name: golang-proxy
    ports:
      - "8080:8080"
    networks:
      - pzero
    environment:
      - ENVIRONMENT=${ENVIRONMENT:-development}
      - DEBUG=${DEBUG:-false}
      - ALLOWED_DOMAINS=${ALLOWED_DOMAINS}
      - CORS_ALLOWED_ORIGIN=${CORS_ALLOWED_ORIGIN}
      - COOKIE_DOMAIN=${COOKIE_DOMAIN}
    restart: unless-stopped

networks:
  pzero:
    external: true
