name: pzero-b2b-envoy
version: "3.9"
services:
  pzero-envoy:
    image: envoyproxy/envoy:v1.30-latest
    container_name: pzero-envoy-proxy
    ports:
      - "8181:8080" # External port for client requests
      - "9901:9901" # Admin interface
    volumes:
      - ./envoy.yaml:/etc/envoy/envoy.yaml:ro
    command: /usr/local/bin/envoy -c /etc/envoy/envoy.yaml
    restart: unless-stopped
    environment:
      - ENVOY_LOG_LEVEL=info
