CREATE EXTENSION if NOT EXISTS plpython3u;

CREATE EXTENSION if NOT EXISTS pgx_ulid;

CREATE EXTENSION if NOT EXISTS hstore;

CREATE EXTENSION if NOT EXISTS citext;

CREATE EXTENSION if NOT EXISTS pgcrypto;

CREATE EXTENSION if NOT EXISTS pg_trgm;

CREATE EXTENSION if NOT EXISTS postgis;
