import {
  IconActivity,
  IconAlertTriangle,
  IconArrowRight,
  IconBrandGithub,
  IconBrandTwitter,
  IconBuilding,
  IconCheck,
  IconChevronLeft,
  IconChevronRight,
  IconCommand,
  IconCreditCard,
  IconDeviceLaptop,
  IconDotsVertical,
  IconEdit,
  IconEye,
  IconFile,
  IconFileText,
  IconHelpCircle,
  IconInfinity,
  IconLayoutDashboard,
  IconLayoutKanban,
  IconLoader2,
  IconLogin,
  IconMoon,
  IconNetwork,
  IconPhoto,
  IconPizza,
  IconPlus,
  type IconProps,
  IconSettings,
  IconShoppingBag,
  IconSun,
  IconTable,
  IconTrash,
  IconUser,
  IconUserCircle,
  IconUserEdit,
  IconUsers,
  IconUserX,
  IconX,
} from '@tabler/icons-react'

export type Icon = React.ComponentType<IconProps>

export const Icons = {
  dashboard: IconLayoutDashboard,
  activity: IconActivity,
  logo: IconCommand,
  login: IconLogin,
  close: IconX,
  product: IconShoppingBag,
  spinner: IconLoader2,
  kanban: IconLayoutKanban,
  chevronLeft: IconChevronLeft,
  chevronRight: IconChevronRight,
  trash: IconTrash,
  employee: IconUserX,
  post: IconFileText,
  page: IconFile,
  userPen: IconUserEdit,
  user2: IconUserCircle,
  media: IconPhoto,
  settings: IconSettings,
  billing: IconCreditCard,
  ellipsis: IconDotsVertical,
  add: IconPlus,
  warning: IconAlertTriangle,
  user: IconUser,
  users: IconUsers,
  building: IconBuilding,
  table: IconTable,
  tree: IconNetwork,
  network: IconNetwork,
  infinity: IconInfinity,
  arrowRight: IconArrowRight,
  help: IconHelpCircle,
  pizza: IconPizza,
  sun: IconSun,
  moon: IconMoon,
  laptop: IconDeviceLaptop,
  github: IconBrandGithub,
  twitter: IconBrandTwitter,
  check: IconCheck,
  moreHorizontal: IconDotsVertical,
  eye: IconEye,
  edit: IconEdit,
}
