import { subDays, subHours } from "date-fns";
import { createSimpleTimeline } from "@/components/data-table/data-table-timeline-cell";
import type { ColumnSchema } from "./types";

export const treeData = [
  {
    name: "Edge Api",
    url: "edge-api.acme.com/health",
    p95: 140,
    public: true,
    active: true,
    regions: ["ams", "gru", "syd"],
    tags: ["api", "enterprise"],
    date: subHours(new Date(), 1),
    timeline: createSimpleTimeline(["Nov 11 - 12", "Nov 13 - 14", "Nov 15 - 16"], 0),
    subRows: [
      {
        name: "Edge Api - Authentication",
        url: "edge-api.acme.com/auth",
        p95: 120,
        public: true,
        active: true,
        regions: ["ams", "gru", "syd"],
        tags: ["api", "auth"],
        date: subHours(new Date(), 1),
      },
      {
        name: "Edge Api - Data Processing",
        url: "edge-api.acme.com/data",
        p95: 160,
        public: true,
        active: true,
        regions: ["ams", "gru", "syd"],
        tags: ["api", "processing"],
        date: subHours(new Date(), 1),
        subRows: [
          {
            name: "Edge Api - Data Processing - Validation",
            url: "edge-api.acme.com/data/validate",
            p95: 80,
            public: true,
            active: true,
            regions: ["ams"],
            tags: ["api", "validation"],
            date: subHours(new Date(), 1),
          },
          {
            name: "Edge Api - Data Processing - Transform",
            url: "edge-api.acme.com/data/transform",
            p95: 240,
            public: true,
            active: true,
            regions: ["gru"],
            tags: ["api", "transform"],
            date: subHours(new Date(), 1),
          },
        ]
      },
    ]
  },
  {
    name: "Lambda Api",
    url: "lambda-api.acme.com/health",
    p95: 203,
    public: true,
    active: true,
    regions: ["ams", "gru", "syd"],
    tags: ["api"],
    date: subHours(new Date(), 10),
    timeline: createSimpleTimeline(["Nov 10 - 11", "Nov 12 - 13", "Nov 14 - 15"], 1),
    subRows: [
      {
        name: "Lambda Api - User Service",
        url: "lambda-api.acme.com/users",
        p95: 180,
        public: true,
        active: true,
        regions: ["ams", "gru"],
        tags: ["api", "users"],
        date: subHours(new Date(), 10),
      },
      {
        name: "Lambda Api - Order Service",
        url: "lambda-api.acme.com/orders",
        p95: 220,
        public: true,
        active: true,
        regions: ["syd"],
        tags: ["api", "orders"],
        date: subHours(new Date(), 10),
      },
    ]
  },
  {
    name: "Marketing",
    url: "acme.com",
    p95: 659,
    public: true,
    active: true,
    regions: ["hkg", "fra", "iad"],
    tags: ["web"],
    date: subDays(new Date(), 1),
    timeline: createSimpleTimeline(["Nov 09 - 10", "Nov 11 - 12", "Nov 13 - 14"], 2),
    subRows: [
      {
        name: "Marketing - Landing Pages",
        url: "acme.com/landing",
        p95: 520,
        public: true,
        active: true,
        regions: ["hkg", "fra"],
        tags: ["web", "landing"],
        date: subDays(new Date(), 1),
      },
      {
        name: "Marketing - Blog",
        url: "acme.com/blog",
        p95: 680,
        public: true,
        active: true,
        regions: ["iad"],
        tags: ["web", "blog"],
        date: subDays(new Date(), 1),
        subRows: [
          {
            name: "Marketing - Blog - Articles",
            url: "acme.com/blog/articles",
            p95: 640,
            public: true,
            active: true,
            regions: ["iad"],
            tags: ["web", "content"],
            date: subDays(new Date(), 1),
          },
          {
            name: "Marketing - Blog - Search",
            url: "acme.com/blog/search",
            p95: 720,
            public: true,
            active: true,
            regions: ["iad"],
            tags: ["web", "search"],
            date: subDays(new Date(), 1),
          },
        ]
      },
    ]
  },
  {
    name: "App",
    url: "app.acme.com",
    p95: 1301,
    public: false,
    active: true,
    regions: ["iad", "fra"],
    tags: ["app"],
    date: subHours(new Date(), 13),
  },
  {
    name: "Dashboard",
    url: "app.acme.com/dashboard",
    p95: 967,
    public: false,
    active: true,
    regions: ["iad", "fra"],
    tags: ["web"],
    date: subHours(new Date(), 28),
    subRows: [
      {
        name: "Dashboard - Analytics Widget",
        url: "app.acme.com/dashboard/analytics",
        p95: 850,
        public: false,
        active: true,
        regions: ["iad"],
        tags: ["web", "analytics"],
        date: subHours(new Date(), 28),
      },
      {
        name: "Dashboard - User Profile",
        url: "app.acme.com/dashboard/profile",
        p95: 1100,
        public: false,
        active: true,
        regions: ["fra"],
        tags: ["web", "profile"],
        date: subHours(new Date(), 28),
      },
    ]
  },
  {
    name: "Documentation",
    url: "docs.acme.com",
    p95: 943,
    public: true,
    active: true,
    regions: ["ams"],
    tags: ["api", "web"],
    date: subDays(new Date(), 6),
  },
] satisfies (ColumnSchema & { subRows?: any[] })[];